project:
  type: website
  output-dir: docs

website:
  title: "Prof M Mendez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project.qmd
        text: Project
      - href: data.qmd
        text: Data
  page-navigation: true

format:
  html:
    theme: cosmo
    toc: true
